default:
  tags:
    - docker

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

variables:
  ALMALINUX9_IMAGE: "registry.esss.lu.se/ecdc/ess-dmsc/docker-almalinux9-conan:1.2.0"
  CENTOS7_IMAGE: "registry.esss.lu.se/ecdc/ess-dmsc/build-nodes/centos7:1.0"
  BUILD_DIR: "build"

stages:
  - build
  - publish


    - conan config install $ESS_CONAN_CONFIG_URL

build:
  stage: build
  image: $CENTOS7_IMAGE
  cache:
    key: "$CI_COMMIT_SHA-$CONTAINER_IMAGE"
    paths:
      - $BUILD_DIR/
  <<: *conan-config
  script:
    - mkdir -p $BUILD_DIR && cd $BUILD_DIR
    - conan install --build missing .. 
    - conan info ../conanfile.txt > CONAN_INFO
    - cmake .. -DBUILD_EVERYTHING=ON
    - make -j$(nproc) all;
  artifacts:
    paths:
      - $BUILD_DIR

unit-tests:
  stage: unit-tests
  image: $CENTOS7_IMAGE
  dependencies:
    - build
  <<: *conan-config
  script:
    - cd $BUILD_DIR
    - chmod +x activate_run.sh
    - ./activate_run.sh
    - cmake .. -DBUILD_EVERYTHING=ON
    - make all unit_tests
    - ./unit_tests/unit_tests --gtest_output=xml:TestResults.xml --gtest_filter=-'GraylogConnectionCom.IPv6ConnectionTest'
    - mv TestResults.xml ../TestResults.xml
  artifacts:
    reports:
      junit: TestResults.xml
    paths:
      - TestResults.xml

publish:
  stage: publish
  image: $CENTOS7_IMAGE
  dependencies:
    - build
  <<: *conan-config
  script:
    - |
      packageNameAndVersion=$(conan inspect --attribute name --attribute version . | awk -F': ' '{print $2}' | paste -sd'/')
    - cd $BUILD_DIR
    - conan export-pkg .. ess-dmsc/stable --build-folder=. --install-folder=.
    - conan user $ESS_ARTIFACTORY_ECDC_CONAN_USER --remote=ecdc-conan-virtual --password=$ESS_ARTIFACTORY_ECDC_CONAN_TOKEN
    - conan upload "${packageNameAndVersion}"@ess-dmsc/stable --confirm --remote ecdc-conan-virtual
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_TAG
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
