default:
  tags:
    - docker

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

stages:
  - build
  - publish

variables:
  ALMALINUX9_IMAGE: "registry.esss.lu.se/ecdc/ess-dmsc/docker-almalinux9-conan:1.2.0"
  CENTOS7_IMAGE: "registry.esss.lu.se/ecdc/ess-dmsc/docker-centos7-conan:1.0.0"
  CONAN_USER_HOME: "$CI_PROJECT_DIR"
  CONAN_CONFIG_REPO: "http://github.com/ess-dmsc/conan-configuration.git"
  CONAN_REMOTE: "ecdc-conan-virtual"

build_centos7:
  stage: build
  image: $CENTOS7_IMAGE
  script:
    - conan config install $CONAN_CONFIG_REPO
    - conan create . ess-dmsc/stable --build=missing --build=hdf5 -pr=linux_x86_64_gcc11_legacy
  artifacts:
    paths:
      - .conan
    expire_in: 1 day

build_almalinux9:
  stage: build
  image: $ALMALINUX9_IMAGE
  script:
    - conan config install $CONAN_CONFIG_REPO
    - conan create . ess-dmsc/stable --build=missing -pr=linux_x86_64_gcc11
  artifacts:
    paths:
      - .conan
    expire_in: 1 day

publish_centos7:
  stage: publish
  image: $ALMALINUX9_IMAGE
  script:
    - conan config install $CONAN_CONFIG_REPO
    - conan user $ESS_ARTIFACTORY_ECDC_CONAN_USER --remote=$CONAN_REMOTE --password=$ESS_ARTIFACTORY_ECDC_CONAN_TOKEN
    - conan upload h5cpp --all -r=$CONAN_REMOTE --confirm
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
    - build_centos7

publish_almalinux9:
  stage: publish
  image: $ALMALINUX9_IMAGE
  script:
    - conan config install $CONAN_CONFIG_REPO
    - conan user $ESS_ARTIFACTORY_ECDC_CONAN_USER --remote=$CONAN_REMOTE --password=$ESS_ARTIFACTORY_ECDC_CONAN_TOKEN
    - conan upload h5cpp --all -r=$CONAN_REMOTE --confirm
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
    - build_almalinux9
